var language = {
  appName: "Product Catalog",
  login: "Login",
  register: "Register",
  email: "E-Mail",
  password: "Password",
  passwordAgain: "Password (again)",
  name: "Name",
  surname: "Surname",
  productDetail: "Product Detail",
  en: "English (İngilizce)",
  tr: "Turkish (Türkçe)",
  addProduct: "Add Product",
  upload: "Upload",
  save: "Save",
  brand: "Brand",
  picture: "Picture",
  pleasePictureSelect: "Please select your product picture",
  category: "Category",
  color: "Color",
  useCase: "Use Case",
  select: "Select...",
  productName: "Product Name",
  productDescription: "Product Description",
  productPrice: "Product Price",
  yes: "Yes",
  no: "No",
  productIsOfferable: "Is Offerable",
  productIsSold: "Is Sold",
  ERR_EXTENSION: "File extension is not accepted",
  ERR_SIZE:
    "The size of the image you are trying to upload is larger than 400 KB",
  ERR_PASSWORD_NOT_EQUAL: "Passwords is not equal",
  ERR_PASSWORD_SHORT: "Passwords is short",
  ERR_PASSWORD_LONG: "Passwords is long",
  logout: "Log out",
  sendOffer: "Send Offer",
  buy: "Buy",
  priceSign: "$",
  user: "User",
  myAccount: "My Account",
  receivedOffers: "Received Offers",
  sentOffers: "Sent Offers",
  myPurchases: "My Purchases",
  quickOffers: "Quick Offers",
  offerPrice: "Offer Price",
};

export default language;
