var language = {
  appName: "Ürün Katalog",
  login: "Giriş Yap",
  register: "Kayıt Ol",
  email: "E-Posta",
  password: "Parola",
  passwordAgain: "Parola (tekrar)",
  name: "İsim",
  surname: "Soyisim",
  productDetail: "Ürün Detayları",
  addToCart: "Sepete Ekle",
  cart: "Sepet",
  en: "İngilizce (English)",
  tr: "Türkçe (Turkish)",
  addProduct: "Ürün Ekle",
  upload: "Yükle",
  save: "Kaydet",
  brand: "Marka",
  picture: "Resim",
  pleasePictureSelect: "Lütfen ürün resminizi seçin",
  category: "Kategori",
  color: "Renk",
  useCase: "Kullanım Durumu",
  select: "Seçiniz...",
  productName: "Ürün İsmi",
  productDescription: "Ürün Açıklaması",
  productPrice: "Ürün Fiyatı",
  yes: "Evet",
  no: "Hayır",
  productIsOfferable: "Teklif Verilebilir",
  ERR_EXTENSION: "Yüklemeye çalıştığınız resmin uzantısı kabul edilmiyor",
  ERR_SIZE: "Yüklemeye çalıştığınız resmin boyutu 400KB'tan büyüktür",
  ERR_PASSWORD_NOT_EQUAL: "Parolalar aynı değil",
  ERR_PASSWORD_SHORT: "Parola kısa",
  ERR_PASSWORD_LONG: "Parola uzun",
  logout: "Çıkış yap",
};

export default language;
