var language = {
  appName: "Ürün Katalog",
  login: "Giriş Yap",
  register: "Kayıt Ol",
  email: "E-Posta",
  password: "Parola",
  passwordAgain: "Parola (tekrar)",
  name: "İsim",
  surname: "Soyisim",
  productDetail: "Ürün Detayları",
  en: "İngilizce (English)",
  tr: "Türkçe (Turkish)",
  addProduct: "Ürün Ekle",
  upload: "Yükle",
  save: "Kaydet",
  brand: "Marka",
  picture: "Resim",
  pleasePictureSelect: "Lütfen ürün resminizi seçin",
  category: "Kategori",
  color: "Renk",
  useCase: "Kullanım Durumu",
  select: "Seçiniz...",
  productName: "Ürün İsmi",
  productDescription: "Ürün Açıklaması",
  productPrice: "Ürün Fiyatı",
  yes: "Evet",
  no: "Hayır",
  productIsOfferable: "Teklif Verilebilir",
  productIsSold: "Satıldı",
  ERR_EXTENSION: "Yüklemeye çalıştığınız resmin uzantısı kabul edilmiyor",
  ERR_SIZE: "Yüklemeye çalıştığınız resmin boyutu 400KB'tan büyüktür",
  ERR_PASSWORD_NOT_EQUAL: "Parolalar aynı değil",
  ERR_PASSWORD_SHORT: "Parola kısa",
  ERR_PASSWORD_LONG: "Parola uzun",
  logout: "Çıkış yap",
  sendOffer: "Teklif Ver",
  buy: "Satın Al",
  priceSign: "$",
  user: "Kullanıcı",
  myAccount: "Hesabım",
  receivedOffers: "Teklif Aldıklarım",
  sentOffers: "Teklif Verdiklerim",
  myPurchases: "Satın Aldıklarım",
  quickOffers: "Hızlı Teklifler",
  offerPrice: "Teklif Fiyatı",
  orderStatus_1: "Teklif Verildi",
  orderStatus_2: "Teklif Onaylandı",
  orderStatus_3: "Satın Alındı",
  showProduct: "Ürünü Görüntüle",
  withdrawOffer: "Teklifi Geri Çek",
  rejectOffer: "Teklifi Reddet",
  acceptOffer: "Accept Offer",
  noData: "Veri yok",
  saleOk: "Satın alma başarıyla gerçekleşti",
  makeBuy: "Satın alma işlemini gerçekleştir",
  success: "İşlem Başarıyla Gerçekleştirildi",
};

export default language;
